### ISSUE TITLE
Crashes on Windows 7 x64

### ISSUE THREAD

**Issue by rob151515** [donSchoe/p2pool-n#4]
Crashing on my Windows 7 64bit box. Followed the instructions and have everything installed (successfully compiled vtc_scrypt.pyd with MinGW) When I run run_p2pool.py with --net vertcoin it gets to 'Initializing work...' then drops back to the command line. The line it's stopping on in main.py is 'yield node.start()'. Windows event log reports application error for python.exe with the faulting module being 'vtc_scrypt.pyd'...

**Comment by erkmos** [comment]
Sounds like your compiler might have compiled broken code. Can you try running this simple testscript http://pastie.org/8722133 with python? Just copy the text into notepad and save it as a somefilename.py and run it with python somefilename.py from the command line (given that you are in the directory containing the file)? If that also crashes then you know that the problem is with the module. What version of MinGW are you using?

**Comment by rob151515** [comment]
Thanks. Ran the script and nothing happens - sits there thinking for a second, then back to command prompt. I downloaded MinGW GUI installer assistant from the getting started page for MinGW: https://sourceforge.net/projects/mingw/files/latest/download
Should have also mentioned that it looks like this test script is crashing with the same event log entries.

**Comment by xMaevy** [comment]
I just tried to install and i get the same problem...

Ive used p2pool on dogecoin and it works flawlessly, but cant seem to get the vtc_scrypt working.

**Comment by erkmos** [comment]
Can you try changing extra_compile_args=['-O3', '-msse3']in setup.py to extra_compile_args=['-O2'] and see if that helps? Not sure what the problem could be since it runs fine on my desktop, but I compile it with msvc. I'll try to setup a vm with mingw and try to reproduce the error if you could give me a little more information about the problem. Maybe a screenshot or pastie of the error message?

**Comment by xMaevy** [comment]
I can confirm that if its compiled with mingw it will fail to start and crash but if you compile it with the other it will work.

**Comment by CartmanSPC** [comment]
the problem may be x64 bit version of python. Try the 32 bit version.

Tips: 1DJPxjc4uDeaPdRpEofNyymbudV8WdozVR
:)

**Comment by evermore** [comment]
I just want to say I had the same issue, and I fixed the issue, I think the problem was I didn't have mingw on my path variable, but I didn't realize subsequent attempts at compiling the app via:

setup.py build --compile=mingw32 install

Did not clear the last built files! I was cached from 2 hours earlier... what a PITA.  So if you have your mingw set up incorrectly and you build it, you can't simply run setup.py build --compile=mingw32 install again.  You have to go into the directory, look for example:

p2pool-vtc-master\py_modules\vertcoin_scrypt\build

and delete everything in there.  THEN try to rerun the setup build.  Haven't used python much so I didn't know it wouldn't replace the first build...

**Comment by donSchoe** [comment]
Fixed https://github.com/donSchoe/p2pool-n/commit/71feda15cf7a728f874ec479af58a6c07f67caff
